# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=40)),
                ('idcardNum', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('education', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=6)),
                ('added_date', models.DateTimeField(verbose_name='date when added')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('ad_date', models.DateTimeField(verbose_name='date when added')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.States'),
        ),
    ]
